version: '3'
services:
  server:
    image: chb1828/assignment-server:latest
    restart: unless-stopped
    environment:
      API_KEY: 77e7e8f5f9666dc4528122342b251327
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/var/log/assignment/server
  client:
    image: chb1828/assignment-client:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/var/log/assignment/client